function auditPanel() { const logs = store.get('auditLogs', [{ action: 'Demo session opened', detail: 'Admin workspace initialized', date: new Date().toISOString() }]); return `<section class="panel"><div class="panel-header"><div><h2>Audit activity</h2><span>Frontend demo activity only</span></div><span class="badge badge-verified">Admin only</span></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Action</th><th>Details</th><th>Time</th></tr></thead><tbody>${logs.map(log => `<tr><td><strong>${escapeHtml(log.action)}</strong></td><td>${escapeHtml(log.detail)}</td><td>${new Date(log.date).toLocaleString('en-NG')}</td></tr>`).join('')}</tbody></table></div></section>`; }
function reportsPanel() { const transaction = store.get('transaction', null); const issues = store.get('maintenanceIssues', []); const notifications = store.get('notifications', []); const verified = properties.filter(property => property.verified).length + store.get('managedProperties', []).filter(property => property.verified).length; const stats = [['Total listings', properties.length + store.get('managedProperties', []).length, 'Marketplace inventory'], ['Verified listings', verified, 'Ready to publish'], ['Caution-fee volume', money(transaction?.amount || 1240000), 'Demo transaction volume'], ['Open support issues', issues.filter(issue => issue.status === 'Open').length, 'Maintenance reports'], ['Notifications', notifications.length, 'Stored activity events']]; return `<section class="panel"><div class="panel-header"><div><h2>Platform reports</h2><span>Derived from local demo state</span></div><button class="btn btn-outline btn-small" data-print-report>Print report</button></div><div class="stats-grid">${stats.map(stat => `<div class="stat-card"><span class="stat-label">${stat[0]}</span><strong class="stat-value">${stat[1]}</strong><span class="stat-note">${stat[2]}</span></div>`).join('')}</div><div class="callout"><strong>Frontend-only report</strong>These figures are mock and local to this browser. A production report would be calculated from verified server-side records.</div></section>`; }
function settingsView() { const settings = store.get('settings', { notifications: true, verification: true, compact: false }); return `${siteHeader()}<main class="section"><div class="section-heading"><div><div class="overline">Admin preferences</div><h2>Settings</h2><p>These controls affect this frontend demo only. No server configuration is changed.</p></div><button class="btn btn-outline btn-small" data-view="home">Back home</button></div><section class="panel" style="max-width:720px"><form id="settings-form"><div class="form-group"><label><input type="checkbox" name="notifications" ${settings.notifications ? 'checked' : ''}> Enable demo notifications</label></div><div class="form-group"><label><input type="checkbox" name="verification" ${settings.verification ? 'checked' : ''}> Require property verification before publishing</label></div><div class="form-group"><label><input type="checkbox" name="compact" ${settings.compact ? 'checked' : ''}> Use compact dashboard density</label></div><div class="callout"><strong>Frontend-only settings</strong>Preferences are stored in localStorage and can be replaced with API-backed settings later.</div><div class="modal-actions" style="justify-content:flex-start"><button class="btn btn-primary" type="submit">Save settings ${icons.arrow}</button><button class="btn btn-outline" type="button" id="reset-demo">Reset demo data</button></div></form></section></main>${siteFooter()}`; }
const store = {
  get(key, fallback) {
    try { return JSON.parse(localStorage.getItem(`weRent_${key}`)) ?? fallback; } catch { return fallback; }
  },
  set(key, value) { localStorage.setItem(`weRent_${key}`, JSON.stringify(value)); }
};

const properties = [
  { id: 'WR-1048', title: 'The Olive Courtyard', location: 'Bodija, Ibadan', type: '3 Bedroom Duplex', price: 2800000, beds: 3, baths: 3, image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=900&q=85', verified: true, owner: 'Adewale Ibrahim', agent: 'ABC Property Agency' },
  { id: 'WR-1052', title: 'Cedar House', location: 'Lekki Phase 1, Lagos', type: '4 Bedroom Detached House', price: 6500000, beds: 4, baths: 4, image: 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=900&q=85', verified: true, owner: 'Ngozi Okafor', agent: 'Mara Homes' },
  { id: 'WR-1061', title: 'Maitama View', location: 'Maitama, Abuja', type: 'Luxury Apartment', price: 4800000, beds: 3, baths: 3, image: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=900&q=85', verified: true, owner: 'Chinedu Obi', agent: 'Northstar Realty' },
  { id: 'WR-1074', title: 'Palm Court', location: 'GRA, Port Harcourt', type: '2 Bedroom Apartment', price: 1900000, beds: 2, baths: 2, image: 'https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=900&q=85', verified: true, owner: 'Tomi Adekunle', agent: 'Ridgepoint Agency' },
  { id: 'WR-1080', title: 'The Green Room', location: 'GRA, Benin City', type: 'Self Contained Apartment', price: 850000, beds: 1, baths: 1, image: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=900&q=85', verified: true, owner: 'Fatima Bello', agent: 'CityNest' },
  { id: 'WR-1088', title: 'Ikeja Garden Flat', location: 'Ikeja, Lagos', type: '2 Bedroom Apartment', price: 2400000, beds: 2, baths: 2, image: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=900&q=85', verified: false, owner: 'Emeka Nwosu', agent: 'Mara Homes' }
];
window.weRentProperties = properties;
const demoUsers = {
  renter: { email: 'renter@werent.test', password: 'password123', name: 'Amaka Eze', role: 'renter' },
  landlord: { email: 'landlord@werent.test', password: 'password123', name: 'Adewale Ibrahim', role: 'landlord' },
  agent: { email: 'agent@werent.test', password: 'password123', name: 'John Properties Agency', role: 'agent' },
  admin: { email: 'admin@werent.test', password: 'password123', name: 'weRent Admin', role: 'admin' }
};
const icons = { home: '⌂', search: '⌕', heart: '♡', applications: '▣', payments: '₦', property: '⌂', users: '♙', shield: '◉', bell: '◌', settings: '⚙', logout: '◉', menu: '☰', arrow: '' };
const roleLabels = { renter: 'Renter workspace', landlord: 'Landlord workspace', agent: 'Agent workspace', admin: 'Admin workspace' };
window.weRentStore = store;
let lastFocusedElement = null;

function money(value) { return `₦${Number(value).toLocaleString('en-NG')}`; }
function currentUser() { return store.get('currentUser', null); }
function initials(name) { return name.split(' ').map(word => word[0]).slice(0, 2).join('').toUpperCase(); }
function navigate(view) { window.location.hash = view; }
function toast(message, type = 'success') {
  const el = document.createElement('div'); el.className = `toast ${type}`; el.textContent = message;
  document.getElementById('toast-region').appendChild(el); setTimeout(() => el.remove(), 3400);
}
function addNotification(title, message) { if (store.get('settings', { notifications: true }).notifications === false) return; const notifications = store.get('notifications', []); notifications.unshift({ id: Date.now(), title, message, read: false, date: new Date().toISOString() }); store.set('notifications', notifications.slice(0, 25)); }
function addAudit(action, detail) { const logs = store.get('auditLogs', []); logs.unshift({ id: Date.now(), action, detail, date: new Date().toISOString() }); store.set('auditLogs', logs.slice(0, 50)); }
function modal(content) {
  lastFocusedElement = document.activeElement;
  document.getElementById('modal-root').innerHTML = `<div class="modal-backdrop" data-close-modal><section class="modal" role="dialog" aria-modal="true">${content}</section></div>`;
  document.querySelector('[data-close-modal]').addEventListener('click', event => { if (event.target.dataset.closeModal !== undefined) closeModal(); });
  setTimeout(() => document.querySelector('.modal button, .modal input, .modal select, .modal textarea')?.focus(), 0);
}
function closeModal() { document.getElementById('modal-root').innerHTML = ''; lastFocusedElement?.focus?.(); lastFocusedElement = null; }
function escapeHtml(value) { return String(value).replace(/[&<>'"]/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#039;', '"': '&quot;' }[char])); }
function toggleMobileMenu(button) { const header = button.closest('.site-header'); const open = header.classList.toggle('menu-open'); button.setAttribute('aria-expanded', String(open)); button.textContent = open ? '×' : icons.menu; }
function setupLazyImages() {
  const images = [...document.querySelectorAll('img[data-src]')].filter(image => !image.closest('[data-hero-carousel]'));
  if (!images.length) return;
  const loadImage = image => {
    if (image.dataset.loaded === 'true') return;
    image.src = image.dataset.src;
    image.dataset.loaded = 'true';
    image.addEventListener('load', () => image.classList.add('is-loaded'), { once: true });
    image.addEventListener('error', () => image.classList.add('is-loaded'), { once: true });
  };
  if (!('IntersectionObserver' in window)) { images.forEach(loadImage); return; }
  const observer = new IntersectionObserver(entries => entries.forEach(entry => {
    if (!entry.isIntersecting) return;
    loadImage(entry.target);
    observer.unobserve(entry.target);
  }), { rootMargin: '200px 0px' });
  images.forEach(image => observer.observe(image));
}
function setupHeroCarousel() {
  const carousel = document.querySelector('[data-hero-carousel]');
  if (!carousel) return;
  const slides = [...carousel.querySelectorAll('.hero-slide')];
  const dots = [...carousel.querySelectorAll('[data-hero-slide]')];
  let active = 0;
  let timer;
  const loadSlideImage = slide => {
    const image = slide.querySelector('img[data-src]');
    if (!image || image.dataset.loaded === 'true') return;
    image.src = image.dataset.src;
    image.dataset.loaded = 'true';
    image.addEventListener('load', () => image.classList.add('is-loaded'), { once: true });
  };
  const showSlide = index => {
    active = (index + slides.length) % slides.length;
    loadSlideImage(slides[active]);
    slides.forEach((slide, slideIndex) => slide.classList.toggle('active', slideIndex === active));
    dots.forEach((dot, dotIndex) => { dot.classList.toggle('active', dotIndex === active); dot.setAttribute('aria-current', dotIndex === active ? 'true' : 'false'); });
  };
  const start = () => { clearInterval(timer); timer = setInterval(() => showSlide(active + 1), 5500); };
  const interact = callback => { callback(); start(); };
  carousel.querySelector('[data-hero-prev]')?.addEventListener('click', () => interact(() => showSlide(active - 1)));
  carousel.querySelector('[data-hero-next]')?.addEventListener('click', () => interact(() => showSlide(active + 1)));
  dots.forEach((dot, index) => dot.addEventListener('click', () => interact(() => showSlide(index))));
  carousel.addEventListener('mouseenter', () => clearInterval(timer));
  carousel.addEventListener('mouseleave', start);
  carousel.addEventListener('focusin', () => clearInterval(timer));
  carousel.addEventListener('focusout', event => { if (!carousel.contains(event.relatedTarget)) start(); });
  showSlide(0);
  setTimeout(() => loadSlideImage(slides[1]), 900);
  start();
}
function setupRolePicker() { const picker = document.querySelector('[data-role-picker]'); if (!picker) return; const trigger = picker.querySelector('.role-picker-trigger'); const select = picker.querySelector('select'); const options = [...picker.querySelectorAll('.role-option')]; const close = () => { picker.classList.remove('open'); trigger.setAttribute('aria-expanded', 'false'); }; trigger.addEventListener('click', () => { const open = picker.classList.toggle('open'); trigger.setAttribute('aria-expanded', String(open)); }); options.forEach(option => option.addEventListener('click', () => { select.value = option.dataset.value; trigger.textContent = option.textContent; options.forEach(item => { const selected = item === option; item.classList.toggle('selected', selected); item.setAttribute('aria-selected', String(selected)); }); select.dispatchEvent(new Event('change', { bubbles: true })); close(); })); document.addEventListener('click', event => { if (!picker.contains(event.target)) close(); }); trigger.addEventListener('keydown', event => { if (event.key === 'Escape') close(); if (event.key === 'ArrowDown' || event.key === 'Enter' || event.key === ' ') { event.preventDefault(); picker.classList.add('open'); trigger.setAttribute('aria-expanded', 'true'); } }); }

function propertyCard(property) {
  const saved = store.get('savedProperties', []).includes(property.id);
  return `<article class="property-card">
    <div class="property-image"><img class="lazy-image" loading="lazy" data-src="${property.image}" alt="${property.title}"><span class="badge ${property.verified ? 'badge-verified' : 'badge-neutral'} image-badge">${property.verified ? '✓ Verified listing' : 'Under review'}</span><button class="favorite ${saved ? 'active' : ''}" data-favorite="${property.id}" aria-label="Save ${property.title}">${saved ? '♥' : '♡'}</button></div>
    <div class="property-body"><span class="location">${property.location}</span><h3>${property.title}</h3><span class="price">${money(property.price)} <small>/ year</small></span><div class="property-meta"><span>▦ ${property.beds} beds</span><span>⌂ ${property.baths} baths</span><span>${property.type.split(' ')[0]}</span></div><button class="btn btn-dark btn-small" data-property="${property.id}">View details ${icons.arrow}</button></div>
  </article>`;
}
function siteHeader() {
  const user = currentUser();
  const guestActions = `<button class="btn btn-ghost btn-small" data-auth="login">Sign in</button><button class="btn btn-primary btn-small" data-auth="signup">Get started</button>`;
  const memberActions = `<a class="btn btn-ghost btn-small" href="#dashboard/overview">${(user?.name || 'User').split(' ')[0]}</a><button class="btn btn-primary btn-small" id="header-signout" type="button">Sign out</button>`;
  return `<header class="site-header"><a class="brand" href="#home"><span class="brand-mark"><span>w</span></span><span>weRent</span></a><nav class="nav-links"><a href="#home">Home</a><a href="#properties">Properties</a><a href="#how-it-works">How it works</a><a href="#about">Why weRent</a></nav><div class="header-actions">${user ? memberActions : guestActions}<button class="mobile-menu" aria-label="Menu" aria-expanded="false">${icons.menu}</button></div></header>`;
}
function homeView() {
  return `${siteHeader()}<main>
    <section class="hero"><div class="hero-carousel" data-hero-carousel aria-label="Featured homes"><div class="hero-slide active"><img fetchpriority="high" src="https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1800&q=85" alt="Modern Nigerian-style home exterior"></div><div class="hero-slide"><img data-src="https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1800&q=85" alt="Bright modern residential interior"></div><div class="hero-slide"><img data-src="https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1800&q=85" alt="Contemporary urban apartment living space"></div><button class="hero-carousel-control prev" type="button" data-hero-prev aria-label="Previous featured home">‹</button><button class="hero-carousel-control next" type="button" data-hero-next aria-label="Next featured home">›</button><div class="hero-carousel-dots">${[0, 1, 2].map(index => `<button type="button" data-hero-slide="${index}" aria-label="Show featured home ${index + 1}" aria-current="${index === 0 ? 'true' : 'false'}" class="${index === 0 ? 'active' : ''}"></button>`).join('')}</div></div><div class="hero-content"><div class="eyebrow">Nigeria's trusted rental network</div><h1>Find a place you'll love to <em>call home.</em></h1><p class="hero-copy">Discover verified homes, transparent applications, and the right people to guide you from first search to move-in.</p><form class="search-panel" id="hero-search"><input name="location" placeholder="Search city, area or property" aria-label="Search location"><select name="type" aria-label="Property type"><option value="">Any property type</option><option>Apartment</option><option>Duplex</option><option>Self Contained</option></select><select name="budget" aria-label="Budget"><option value="">Any budget</option><option value="2000000">Under ₦2m</option><option value="5000000">Under ₦5m</option></select><button class="btn btn-lime" type="submit">Find a home ${icons.arrow}</button></form><div class="trust-row"><span class="trust-item"><i class="trust-icon">✓</i> Verified listings</span><span class="trust-item"><i class="trust-icon">◌</i> Direct contact</span><span class="trust-item"><i class="trust-icon">₦</i> Clear payments</span></div></div></section>
    <section class="section" id="properties"><div class="section-heading"><div><div class="overline">Curated for you</div><h2>Homes worth coming home to.</h2><p>Explore quality spaces in the places people are moving to next.</p></div><button class="btn btn-outline btn-small" data-view="properties">Browse all properties ${icons.arrow}</button></div><div class="property-grid">${properties.slice(0, 3).map(propertyCard).join('')}</div></section>
    <section class="section" id="how-it-works"><div class="section-heading"><div><div class="overline">A clearer way to rent</div><h2>Move with confidence.</h2><p>From your first search to your first night, we keep the process visible and human.</p></div></div><div class="type-grid"><div class="type-card"><span class="type-symbol">⌕</span><div><h3>Search verified homes</h3><span>Real listings, real locations</span></div></div><div class="type-card"><span class="type-symbol">▣</span><div><h3>Apply in one place</h3><span>Documents and updates together</span></div></div><div class="type-card"><span class="type-symbol">◌</span><div><h3>Meet your agent</h3><span>Guidance when it matters</span></div></div><div class="type-card"><span class="type-symbol">₦</span><div><h3>Pay with clarity</h3><span>Caution fee held by your agent</span></div></div></div></section>
    <section class="section split-band" id="about"><div><div class="overline">More than a listing</div><h2>Good rentals start with good information.</h2><div class="feature-list"><div><span class="step-number">01</span><div><h3>Verification-first listings</h3><p>See clearer property details and understand who owns and manages the rental.</p></div></div><div><span class="step-number">02</span><div><h3>One application timeline</h3><p>Track documents, inspections, approvals, and payments without chasing updates.</p></div></div><div><span class="step-number">03</span><div><h3>People you can reach</h3><p>Connect with landlords and assigned agents directly, with every responsibility made clear.</p></div></div></div></div><div class="editorial-image"><img class="lazy-image" loading="lazy" data-src="https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1000&q=85" alt="Modern home interior"><div class="editorial-label"><div><strong>The Olive Courtyard</strong><small>Bodija, Ibadan · 3 beds</small></div><span class="badge badge-verified">✓ Verified</span></div></div></section>
    <section class="section"><div class="section-heading"><div><div class="overline">Built around trust</div><h2>The details make the difference.</h2></div></div><div class="benefit-grid"><div class="benefit-card"><span class="type-symbol">◉</span><h3>Verified properties</h3><p>Know what has been checked before you book a viewing.</p></div><div class="benefit-card"><span class="type-symbol">▤</span><h3>Application tracking</h3><p>See exactly where your application stands, at every step.</p></div><div class="benefit-card"><span class="type-symbol">♙</span><h3>Clear ownership</h3><p>Property owners and assigned agents have distinct roles.</p></div><div class="benefit-card"><span class="type-symbol">✦</span><h3>Human support</h3><p>Get help when a rental question needs more than a search.</p></div></div></section>
    <section class="section"><div class="cta-band"><div class="cta-panel"><h3>Looking for a property?</h3><p>Search rentals that fit your life and move forward with less guesswork.</p><button class="btn btn-lime" data-view="properties">Browse homes ${icons.arrow}</button></div><div class="cta-panel dark"><h3>Have a property to list?</h3><p>Reach serious renters and manage interest from one calm workspace.</p><button class="btn btn-lime" data-auth="signup">List your property ${icons.arrow}</button></div></div></section>
  </main>${siteFooter()}`;
}
function infoPageView(kind) {
  const pages = {
    about: { eyebrow: 'About weRent', title: 'A clearer way to find your next address.', copy: 'weRent brings renters, property owners, and trusted agents into one visible rental journey.', content: '<div class="benefit-grid"><div class="benefit-card"><span class="type-symbol">✓</span><h3>Verification first</h3><p>Clearer property details help renters make confident decisions.</p></div><div class="benefit-card"><span class="type-symbol">▣</span><h3>One connected journey</h3><p>Applications, inspections, and payment updates stay together.</p></div><div class="benefit-card"><span class="type-symbol">♙</span><h3>People you can reach</h3><p>Renters know who owns and manages each property.</p></div></div>' },
    privacy: { eyebrow: 'Privacy policy', title: 'Your rental information stays in your hands.', copy: 'This frontend demo stores sample activity locally in your browser. No real payments are processed and no information is sent to a production service from this page.', content: '<section class="panel"><h3>What this demo stores</h3><p>Saved homes, demo profile details, applications, and workflow activity may be stored in your browser local storage so the prototype can remember your progress.</p><h3>What you control</h3><p>You can clear this demo data through your browser storage controls or the reset option in the workspace settings.</p></section>' },
    support: { eyebrow: 'Support', title: 'Help for the next step in your move.', copy: 'Find answers about listings, applications, inspections, and the rental workflow.', content: '<div class="cta-band"><div class="cta-panel"><h3>Looking for a home?</h3><p>Browse verified listings and keep your applications in one place.</p><a class="btn btn-lime" href="#properties">Browse properties</a></div><div class="cta-panel dark"><h3>Need account help?</h3><p>Sign in or create an account to access your rental workspace.</p><a class="btn btn-lime" href="#auth-login">Open sign in</a></div></div>' },
    owners: { eyebrow: 'For owners', title: 'Turn your property into a better rental experience.', copy: 'Create an owner or agent account to list homes, review interest, and manage your rental workflow.', content: '<div class="cta-band"><div class="cta-panel"><h3>List a property</h3><p>Start an owner account and add your first listing.</p><a class="btn btn-lime" href="#list-property">Create owner account</a></div><div class="cta-panel dark"><h3>Meet an agent</h3><p>Join as an agent and manage assigned properties and renters.</p><a class="btn btn-lime" href="#meet-agent">Join as an agent</a></div></div>' },
    listProperty: { eyebrow: 'List a property', title: 'Give your property the attention it deserves.', copy: 'Create an owner account to publish a listing, review renter interest, and manage your property from one workspace.', content: '<section class="panel"><h3>Ready to list?</h3><p>Set up your owner profile and add property details, images, pricing, and availability.</p><a class="btn btn-primary" href="#auth-signup">Create owner account</a></section>' },
    meetAgent: { eyebrow: 'Meet an agent', title: 'Find the right person to help your rental move forward.', copy: 'Join weRent as an agent to manage assigned properties, guide renters, and keep every step visible.', content: '<section class="panel"><h3>Become a weRent agent</h3><p>Create an agent account to connect with property owners and support renters through applications and inspections.</p><a class="btn btn-primary" href="#auth-signup">Join as an agent</a></section>' }
  }[kind];
  if (!pages) return homeView();
  return `${siteHeader()}<main class="section"><div class="section-heading"><div><div class="overline">${pages.eyebrow}</div><h2>${pages.title}</h2><p>${pages.copy}</p></div><a class="btn btn-outline btn-small" href="#home">Back home</a></div>${pages.content}</main>${siteFooter()}`;
}
function siteFooter() { return `<footer class="footer"><div class="footer-top"><div><a class="brand" href="#home"><span class="brand-mark"><span>w</span></span><span>weRent</span></a><p>A clearer Nigerian rental marketplace for renters, landlords, and the people who help them move.</p></div><div><h4>Explore</h4><ul><li><a href="#properties">Find a property</a></li><li><a href="#how-it-works">How it works</a></li><li><a href="#auth-signup">Join weRent</a></li></ul></div><div><h4>For owners</h4><ul><li><a href="#list-property">List a property</a></li><li><a href="#meet-agent">Meet an agent</a></li><li><a href="#dashboard/overview">Owner dashboard</a></li></ul></div><div><h4>Company</h4><ul><li><a href="#company-about">About weRent</a></li><li><a href="#privacy-policy">Privacy policy</a></li><li><a href="#support">Support</a></li></ul></div></div><div class="footer-bottom"><span>© 2026 weRent. Built for better renting in Nigeria.</span><span>Frontend demo · No real payments are processed</span></div></footer>`; }

function filterProperties({ location = '', type = '', verified = '', budget = '' } = {}) { const query = String(location).toLowerCase().trim(); return properties.filter(property => (!query || `${property.title} ${property.location}`.toLowerCase().includes(query)) && (!type || property.type.includes(type)) && (!verified || property.verified) && (!budget || property.price <= Number(budget))); }
function propertiesView(queryString = '') { const params = new URLSearchParams(queryString); const filters = { location: params.get('location') || '', type: params.get('type') || '', verified: params.get('verified') || '', budget: params.get('budget') || '' }; const results = filterProperties(filters); const layout = store.get('propertyLayout', 'grid'); const options = type => properties.some(property => property.type.includes(type)) ? `<option value="${type}" ${filters.type === type ? 'selected' : ''}>${type}</option>` : ''; return `${siteHeader()}<main class="section"><div class="section-heading"><div><div class="overline">Marketplace</div><h2>Find your next address.</h2><p id="results-copy">${results.length} homes match your search</p></div><div style="display:flex;align-items:center;gap:10px"><div class="view-switcher" aria-label="Property view"><button type="button" class="${layout === 'grid' ? 'active' : ''}" data-layout="grid">▦ Grid</button><button type="button" class="${layout === 'list' ? 'active' : ''}" data-layout="list">☷ List</button></div><button class="btn btn-outline btn-small" data-view="home">Back home</button></div></div><form class="panel" id="filter-form" style="margin-bottom:24px;display:grid;grid-template-columns:2fr 1fr 1fr 1fr auto;gap:10px"><input name="location" value="${escapeHtml(filters.location)}" placeholder="Search by city or area"><select name="type"><option value="">All property types</option>${options('Apartment')}${options('Duplex')}${options('Self Contained')}${options('House')}</select><select name="budget"><option value="">Any budget</option><option value="2000000" ${filters.budget === '2000000' ? 'selected' : ''}>Under ₦2m</option><option value="5000000" ${filters.budget === '5000000' ? 'selected' : ''}>Under ₦5m</option></select><select name="verified"><option value="">Any listing</option><option value="true" ${filters.verified === 'true' ? 'selected' : ''}>Verified only</option></select><button class="btn btn-primary" type="submit">Filter</button></form><div class="property-grid ${layout === 'list' ? 'list-view' : ''}" id="property-results">${results.length ? results.map(propertyCard).join('') : '<div class="panel empty-state" style="grid-column:1/-1"><div class="empty-icon">⌕</div><strong>No matching homes found.</strong><p>Try a different city, property type, or budget.</p></div>'}</div></main>${siteFooter()}`; }
function authView(mode = 'login') { const signup = mode === 'signup'; return `<div class="auth-layout"><aside class="auth-aside"><a class="brand" href="#home"><span class="brand-mark"><span>w</span></span><span>weRent</span></a><h1>${signup ? 'A better move starts here.' : 'Welcome back to your next home.'}</h1><p>${signup ? 'Create your free account and keep the whole rental journey in one place.' : 'Pick up where you left off, from saved homes to active applications.'}</p></aside><main class="auth-main"><div class="form-card"><a class="text-link" href="#home">Back to weRent</a><h2>${signup ? 'Create your account' : 'Sign in'}</h2><p>${signup ? 'Choose the workspace that fits how you rent.' : 'Use a demo account below to explore the prototype.'}</p><form id="auth-form"><div class="form-group"><label for="email">Email address</label><input id="email" type="email" name="email" required placeholder="you@example.com"></div><div class="form-group"><label for="password">Password</label><input id="password" type="password" name="password" required minlength="6" placeholder="Minimum 6 characters"></div>${signup ? '<div class="form-group"><label for="name">Full name</label><input id="name" name="name" required placeholder="Your full name"></div><div class="form-group"><label for="role">I am joining as</label><div class="role-picker" data-role-picker><select id="role" name="role" class="native-role-select"><option value="renter">Renter</option><option value="landlord">Landlord</option><option value="agent">Agent</option></select><button type="button" class="role-picker-trigger" aria-haspopup="listbox" aria-expanded="false">Renter</button><div class="role-picker-menu" role="listbox" aria-label="Account role"><button type="button" class="role-option selected" role="option" data-value="renter" aria-selected="true">Renter</button><button type="button" class="role-option" role="option" data-value="landlord" aria-selected="false">Landlord</button><button type="button" class="role-option" role="option" data-value="agent" aria-selected="false">Agent</button></div></div></div>' : ''}<div class="form-actions"><a class="text-link" href="#auth-forgot">Forgot password?</a><button class="btn btn-primary" type="submit">${signup ? 'Create account' : 'Sign in'}</button></div></form>${!signup ? `<div class="demo-box"><strong>Demo accounts</strong><br>Renter: renter@werent.test<br>Landlord: landlord@werent.test<br>Agent: agent@werent.test<br>Admin: admin@werent.test<br>Password: password123</div>` : '<p style="margin-top:22px">Already have an account? <a class="text-link" href="#auth-login">Sign in</a></p>'}</div></main></div>`; }
function forgotPasswordView() { return `<div class="auth-layout"><aside class="auth-aside"><a class="brand" href="#home"><span class="brand-mark"><span>w</span></span><span>weRent</span></a><h1>Get back to moving forward.</h1><p>Enter your email and we will simulate a reset link for this frontend demo.</p></aside><main class="auth-main"><div class="form-card"><a class="text-link" href="#auth-login">Back to sign in</a><h2>Reset your password</h2><p>We will send a demo reset message. No email is actually sent.</p><form id="forgot-form"><div class="form-group"><label for="reset-email">Email address</label><input id="reset-email" name="email" type="email" required placeholder="you@example.com"></div><button class="btn btn-primary" type="submit">Send reset link</button></form></div></main></div>`; }

const sidebarGlyphs = { home: '⌂', search: '⌕', heart: '♡', applications: '▣', payments: '₦', property: '⌂', users: '♙', notifications: '◌', tenancy: '⌂', messages: '✉', refunds: 'R', disputes: '⚑', audit: '▤', reports: '▥' };
function sideLink(icon, label, view, active) { const glyph = sidebarGlyphs[icon] || icon; return `<a href="#dashboard/${view}" class="side-link ${active === view ? 'active' : ''}" aria-label="${label}" title="${label}"><span aria-hidden="true">${glyph}</span><span>${label}</span></a>`; }
function dashboardView(section = 'overview') { const user = currentUser() || demoUsers.renter; const role = user.role; const active = section; const nav = role === 'renter' ? [['home','Overview','overview'],['search','Search properties','properties'],['♡','Saved homes','saved'],['▣','Applications','applications'],['₦','Payments','payments'],['⌂','Tenancy','tenancy'],['✉','Messages','messages'],['◌','Notifications','notifications']] : role === 'landlord' ? [['home','Overview','overview'],['⌂','My properties','properties'],['▣','Applications','applications'],['♙','Renters','renters'],['₦','Transactions','transactions'],['✉','Messages','messages'],['◌','Notifications','notifications']] : role === 'agent' ? [['home','Overview','overview'],['⌂','Assigned properties','properties'],['▣','Applications','applications'],['♙','Renters','renters'],['₦','Caution fees','payments'],['R','Refunds','refunds'],['✉','Messages','messages'],['⚑','Disputes','disputes']] : [['home','Overview','overview'],['♙','Users','users'],['⌂','Properties','properties'],['▣','Applications','applications'],['₦','Transactions','transactions'],['R','Refunds','refunds'],['⚑','Disputes','disputes'],['▤','Audit logs','audit'],['▥','Reports','reports']]; return `<div class="dashboard"><aside class="sidebar"><a class="brand" href="#dashboard/overview"><span class="brand-mark"><span>w</span></span><span>weRent</span></a><div class="sidebar-role">${roleLabels[role]}</div><nav>${nav.map(item => sideLink(item[0], item[1], item[2], active)).join('')}</nav><div class="sidebar-bottom"><a class="side-link" href="#dashboard/profile"><span>♙</span><span>Profile</span></a><button class="side-link" id="logout" style="width:100%;border:0;background:transparent;text-align:left"><span>${icons.logout}</span><span>Sign out</span></button></div></aside><main class="dashboard-main"><header class="dashboard-header"><h1>${dashboardTitle(role, section)}</h1><div class="user-chip"><span>${user.name}</span><span class="avatar">${initials(user.name)}</span></div></header><div class="dashboard-content">${dashboardContent(role, section)}</div></main></div>`; }
function dashboardTitle(role, section) { const titles = { overview: role === 'agent' ? 'Caution fee overview' : 'Good morning', properties: 'Properties', applications: 'Applications', payments: role === 'agent' ? 'Caution fee management' : 'Payments', tenancy: 'Current tenancy', messages: 'Messages', profile: 'Profile settings', audit: 'Audit logs', reports: 'Reports', refunds: 'Refund requests', disputes: 'Dispute centre', users: 'User management', renters: 'Renters', transactions: 'Transactions', saved: 'Saved properties', notifications: 'Notifications' }; return titles[section] || 'Workspace'; }
function dashboardContent(role, section) { if (section === 'properties' && role === 'renter') {
  const initialResults = properties;
  return `<section class="panel" style="margin-bottom:24px"><div class="panel-header"><div><h2>Search available homes</h2><span>Filter by city, type, and budget</span></div></div><form class="panel" id="filter-form" style="margin-bottom:0;display:grid;grid-template-columns:2fr 1fr 1fr 1fr auto;gap:10px"><input name="location" placeholder="Search by city or area"><select name="type"><option value="">All property types</option><option>Apartment</option><option>Duplex</option><option>Self Contained</option></select><select name="budget"><option value="">Any budget</option><option value="2000000">Under ₦2m</option><option value="5000000">Under ₦5m</option></select><select name="verified"><option value="">Any listing</option><option value="true">Verified only</option></select><button class="btn btn-primary" type="submit">Apply filters</button></form></section><div class="section-heading" style="margin: 0 0 18px;"><div><p id="results-copy" style="margin:0;">${initialResults.length} homes match your search</p></div></div><div id="property-results" class="property-grid">${initialResults.map(propertyCard).join('')}</div>`;
} if (section === 'properties' && ['landlord', 'agent'].includes(role)) return managedPropertiesPanel(role); if (section === 'properties' && role === 'admin') return adminPropertiesPanel(); if (section === 'saved') { const saved = properties.filter(p => store.get('savedProperties', []).includes(p.id)); return saved.length ? `<div class="property-grid">${saved.map(propertyCard).join('')}</div>` : `<div class="panel empty-state"><div class="empty-icon">♡</div><strong>You haven't saved any homes yet.</strong><p>Tap the heart on a property to keep it here.</p></div>`; } if (section === 'payments' && role === 'renter') return renterPayments(); if (section === 'tenancy' && role === 'renter') return tenancyPanel(); if (section === 'messages') return messagesPanel(role); if (section === 'profile') return profilePanel(); if (section === 'audit' && role === 'admin') return auditPanel(); if (section === 'reports' && role === 'admin') return reportsPanel(); if (section === 'refunds') return refundTable(role); if (section === 'transactions' || (section === 'payments' && role === 'agent')) return transactionsTable(role); if (section === 'applications') return applicationsPanel(role); if (section === 'disputes') return disputesPanel(); if (section === 'users') return usersPanel(); if (section === 'notifications') return notificationsPanel(); return overviewPanel(role); }
function overviewPanel(role) { const isAgent = role === 'agent'; const stats = isAgent ? [['Held caution fees','₦1,240,000','+ ₦200,000 this month'],['Pending confirmation','3','Needs your review'],['Refund requests','2','1 awaiting admin'],['Active rentals','18','Across 6 properties']] : role === 'landlord' ? [['Active properties','4','+1 this month'],['Applications','12','5 new this week'],['Occupied units','9','82% occupancy'],['Transactions','₦7.8m','Property activity']] : role === 'admin' ? [['Platform users','1,284','+12% this month'],['Properties','438','92% verified'],['Transactions','₦48.2m','All time volume'],['Open disputes','7','Needs attention']] : [['Active applications','2','1 needs your action'],['Saved properties','6','Across 3 cities'],['Pending payments','₦200,000','Awaiting caution fee'],['Upcoming inspections','1','Tomorrow, 10:00am']]; return `<div class="stats-grid">${stats.map(stat => `<div class="stat-card"><span class="stat-label">${stat[0]}</span><strong class="stat-value">${stat[1]}</strong><span class="stat-note">${stat[2]}</span></div>`).join('')}</div><div class="dashboard-grid"><section class="panel"><div class="panel-header"><h2>${isAgent ? 'Recent caution-fee activity' : 'Your rental journey'}</h2><span>Updated just now</span></div>${isAgent ? transactionRows() : `<div class="timeline"><div class="timeline-item"><span class="timeline-dot">✓</span><div><strong>Application submitted</strong><small>The Olive Courtyard · 2 days ago</small></div><span class="status success">Complete</span></div><div class="timeline-item"><span class="timeline-dot">◌</span><div><strong>Inspection scheduled</strong><small>The Olive Courtyard · Tomorrow, 10:00am</small></div><span class="status warning">Upcoming</span></div><div class="timeline-item"><span class="timeline-dot">₦</span><div><strong>Caution fee</strong><small>Paid to ABC Property Agency</small></div><span class="status">Awaiting</span></div></div>`}</section><section class="panel"><div class="panel-header"><h2>Important distinction</h2></div><div class="callout"><strong>Property owner and payment recipient</strong>The landlord owns the property. Your assigned agent receives and manages the caution fee for this rental transaction.</div><div style="margin-top:18px"><button class="btn btn-primary btn-small" data-view="properties">Explore homes ${icons.arrow}</button></div></section></div>`; }
function workflowState() { return { application: store.get('application', { propertyId: 'WR-1048', status: 'Awaiting Caution Fee' }), transaction: store.get('transaction', null), refund: store.get('refundRequest', null) }; }
function statusClass(status) { return ['Successful', 'Confirmed', 'Approved', 'Refunded'].includes(status) ? 'success' : ['Rejected', 'Refund Rejected'].includes(status) ? 'danger' : 'warning'; }
function updateWorkflow(action, propertyId) { const state = workflowState(); if (action === 'agent-review-application') { state.application.status = 'Document Review'; store.set('application', state.application); addNotification('Documents under review', 'The assigned agent is reviewing your application.'); toast('Application moved to document review.'); } if (action === 'schedule-inspection') { state.application.status = 'Inspection Scheduled'; store.set('application', state.application); store.set('inspection', { date: 'Tomorrow', time: '10:00am', status: 'Scheduled' }); addNotification('Inspection scheduled', 'Your inspection is tomorrow at 10:00am.'); toast('Inspection scheduled for tomorrow at 10:00am.'); } if (action === 'request-caution-fee') { state.application.status = 'Awaiting Caution Fee'; store.set('application', state.application); addNotification('Caution fee requested', 'Your assigned agent is waiting for the caution-fee payment.'); toast('Caution-fee request sent to the renter.'); } if (action === 'confirm-payment' && state.transaction) { state.transaction.status = 'Confirmed'; state.application.status = 'Caution Fee Paid'; store.set('transaction', state.transaction); store.set('application', state.application); addNotification('Caution fee confirmed', 'Your assigned agent confirmed the caution-fee payment.'); toast('Payment confirmed and application updated.'); } if (action === 'approve-application') { state.application.status = 'Approved'; store.set('application', state.application); addNotification('Application approved', 'Your rental application has been approved.'); toast('Application approved successfully.'); } if (action === 'verify-property') { const managed = store.get('managedProperties', []); const property = managed.find(item => item.id === propertyId); if (property) { property.verified = true; store.set('managedProperties', managed); addNotification('Property verified', `${property.title} is now published on weRent.`); toast('Property verified and published.'); } } if (action === 'agent-review-refund' && state.refund) { state.refund.status = 'Pending Admin Approval'; store.set('refundRequest', state.refund); addNotification('Refund forwarded', 'Your refund request is awaiting admin approval.'); toast('Refund forwarded to admin review.'); } if (action === 'admin-approve-refund' && state.refund) { state.refund.status = 'Refunded'; store.set('refundRequest', state.refund); addNotification('Refund processed', 'Your caution-fee refund has been marked as refunded.'); toast('Refund marked as processed.'); } render(); }
function transactionRows(role = 'agent') { const state = workflowState(); const transaction = state.transaction || { amount: 200000, status: 'Pending', id: 'TX-DEMO' }; const action = role === 'agent' && transaction.status === 'Successful' ? '<button class="btn btn-primary btn-small" data-workflow="confirm-payment">Confirm payment</button>' : role === 'admin' && state.application.status === 'Caution Fee Paid' ? '<button class="btn btn-primary btn-small" data-workflow="approve-application">Approve</button>' : '<span class="status">No action</span>'; return `<div class="table-wrap"><table class="data-table"><thead><tr><th>Renter / property</th><th>Amount</th><th>Status</th><th>Action</th></tr></thead><tbody><tr><td><strong>Amaka Eze</strong><br><small>The Olive Courtyard · Adewale Ibrahim</small></td><td>${money(transaction.amount)}</td><td><span class="status ${statusClass(transaction.status)}">${transaction.status}</span></td><td>${action}</td></tr><tr><td><strong>David Obi</strong><br><small>Palm Court · Tomi Adekunle</small></td><td>${money(180000)}</td><td><span class="status success">Confirmed</span></td><td><span class="status">Complete</span></td></tr></tbody></table></div>`; }
function applicationsPanel(role = 'renter') { const state = workflowState(); const status = state.application.status; const action = role === 'renter' && status === 'Awaiting Caution Fee' ? '<button class="btn btn-primary btn-small" data-payment>Pay fee</button>' : role === 'agent' && status === 'Submitted' ? '<button class="btn btn-primary btn-small" data-workflow="agent-review-application">Review documents</button>' : role === 'agent' && status === 'Document Review' ? '<button class="btn btn-primary btn-small" data-workflow="schedule-inspection">Schedule inspection</button>' : role === 'agent' && status === 'Inspection Scheduled' ? '<button class="btn btn-primary btn-small" data-workflow="request-caution-fee">Request caution fee</button>' : role === 'agent' && state.transaction?.status === 'Successful' ? '<button class="btn btn-primary btn-small" data-workflow="confirm-payment">Confirm payment</button>' : '<button class="btn btn-outline btn-small">View</button>'; return `<section class="panel"><div class="panel-header"><h2>Applications</h2><span>Live workflow</span></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Property</th><th>Applicant</th><th>Stage</th><th>Action</th></tr></thead><tbody><tr><td><strong>The Olive Courtyard</strong><br><small>Ibadan · ₦2.8m/year</small></td><td>Amaka Eze</td><td><span class="status ${statusClass(status)}">${status}</span></td><td>${action} <button class="btn btn-outline btn-small" data-application-details>Details</button></td></tr><tr><td><strong>Palm Court</strong><br><small>Port Harcourt · ₦1.9m/year</small></td><td>David Obi</td><td><span class="status success">Approved</span></td><td><button class="btn btn-outline btn-small">View</button></td></tr></tbody></table></div></section>`; }
function transactionsTable(role = 'agent') { return `<section class="panel"><div class="panel-header"><h2>Transaction history</h2><button class="btn btn-outline btn-small">Export CSV</button></div>${transactionRows(role)}<div class="callout" style="margin-top:19px"><strong>Caution fee recipient: assigned agent</strong>Every transaction is linked to a landlord as property owner and an agent as the fee holder.</div></section>`; }
function managedPropertiesPanel(role) { const managed = store.get('managedProperties', role === 'landlord' ? properties.filter(property => property.owner === currentUser()?.name) : properties.slice(0, 3)); return `<section class="panel"><div class="panel-header"><div><h2>${role === 'landlord' ? 'My properties' : 'Assigned properties'}</h2><span>${managed.length} active listings</span></div>${role === 'landlord' ? '<button class="btn btn-primary btn-small" data-add-property>+ Add property</button>' : ''}</div><div class="property-grid">${managed.length ? managed.map(property => role === 'landlord' ? `<div>${propertyCard(property)}<div style="display:flex;gap:8px;margin-top:8px"><button class="btn btn-outline btn-small" data-edit-property="${property.id}">Edit listing</button><button class="btn btn-outline btn-small" data-toggle-property="${property.id}">${property.active === false ? 'Activate' : 'Deactivate'}</button></div></div>` : propertyCard(property)).join('') : '<div class="empty-state" style="grid-column:1/-1"><div class="empty-icon">⌂</div><strong>No properties yet</strong><p>Add your first listing to start managing it.</p></div>'}</div></section>`; }
function adminPropertiesPanel() { const managed = store.get('managedProperties', []); const pending = managed.filter(property => !property.verified); return `<section class="panel"><div class="panel-header"><div><h2>Property verification</h2><span>${pending.length} listings awaiting review</span></div><span class="badge badge-verified">Admin review</span></div>${pending.length ? `<div class="table-wrap"><table class="data-table"><thead><tr><th>Property</th><th>Owner</th><th>Rent</th><th>Status</th><th>Action</th></tr></thead><tbody>${pending.map(property => `<tr><td><strong>${escapeHtml(property.title)}</strong><br><small>${escapeHtml(property.location)}</small></td><td>${escapeHtml(property.owner)}</td><td>${money(property.price)}</td><td><span class="status warning">Under review</span></td><td><button class="btn btn-primary btn-small" data-workflow="verify-property" data-property-id="${property.id}">Verify</button></td></tr>`).join('')}</tbody></table></div>` : '<div class="empty-state"><div class="empty-icon">✓</div><strong>Everything is reviewed</strong><p>No property listings are waiting for verification.</p></div>'}</section>`; }
function renterPayments() { const transaction = store.get('transaction', null); const paid = transaction?.status === 'Successful'; return `<section class="panel"><div class="panel-header"><h2>Caution fee payments</h2><span>Frontend simulation</span></div><div class="payment-summary"><div class="payment-row"><span>Property</span><strong>The Olive Courtyard</strong></div><div class="payment-row"><span>Property owner</span><strong>Adewale Ibrahim</strong></div><div class="payment-row"><span>Caution fee recipient</span><strong style="color:var(--green)">ABC Property Agency (assigned agent)</strong></div><div class="payment-row"><span>Amount</span><strong>${money(200000)}</strong></div><div class="payment-row"><span>Status</span><span class="status ${paid ? 'success' : 'warning'}">${paid ? 'Successful' : 'Awaiting payment'}</span></div></div>${paid ? `<button class="btn btn-primary" data-receipt>View payment receipt ${icons.arrow}</button>` : `<button class="btn btn-primary" data-payment>Pay caution fee to assigned agent ${icons.arrow}</button>`}</section>`; }
function tenancyPanel() { const application = workflowState().application; if (application.status !== 'Approved') return `<section class="panel empty-state"><div class="empty-icon">⌂</div><strong>Your tenancy will appear here after approval.</strong><p>Your application is currently at <b>${escapeHtml(application.status)}</b>. We will keep the move-in details ready for you.</p><button class="btn btn-outline btn-small" data-view="applications">View application</button></section>`; const issues = store.get('maintenanceIssues', []); return `<div class="dashboard-grid"><section class="panel"><div class="panel-header"><h2>Active tenancy</h2><span class="status success">Approved</span></div><div class="payment-summary"><div class="payment-row"><span>Property</span><strong>The Olive Courtyard</strong></div><div class="payment-row"><span>Move-in date</span><strong>15 September 2026</strong></div><div class="payment-row"><span>Annual rent</span><strong>${money(2800000)}</strong></div><div class="payment-row"><span>Property owner</span><strong>Adewale Ibrahim</strong></div><div class="payment-row"><span>Assigned agent</span><strong>ABC Property Agency</strong></div></div></section><section class="panel"><div class="panel-header"><h2>Need support?</h2><span>${issues.length} issue${issues.length === 1 ? '' : 's'} reported</span></div><div class="callout"><strong>Your rental contacts</strong>The assigned agent manages the transaction and remains your first point of contact for move-in coordination.</div><div class="modal-actions" style="justify-content:flex-start"><button class="btn btn-primary btn-small" data-maintenance>Report an issue</button><button class="btn btn-outline btn-small" data-view="notifications">View updates</button></div></section></div>`; }
function refundTable(role = 'agent') { const refund = workflowState().refund || { status: 'Refund Requested' }; const action = role === 'agent' && refund.status === 'Refund Requested' ? '<button class="btn btn-primary btn-small" data-workflow="agent-review-refund">Review</button>' : role === 'admin' && refund.status === 'Pending Admin Approval' ? '<button class="btn btn-primary btn-small" data-workflow="admin-approve-refund">Approve refund</button>' : '<span class="status">Tracked</span>'; return `<section class="panel"><div class="panel-header"><h2>Refund requests</h2><span>Workflow status</span></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Request</th><th>Amount</th><th>Stage</th><th>Action</th></tr></thead><tbody><tr><td><strong>RF-2026-014</strong><br><small>Amaka Eze · The Olive Courtyard</small></td><td>${money(200000)}</td><td><span class="status ${statusClass(refund.status)}">${refund.status}</span></td><td>${action}</td></tr><tr><td><strong>RF-2026-012</strong><br><small>David Obi · Palm Court</small></td><td>${money(180000)}</td><td><span class="status success">Refunded</span></td><td><span class="status">Complete</span></td></tr></tbody></table></div></section>`; }
function disputesPanel() { return `<section class="panel"><div class="panel-header"><h2>Dispute centre</h2><button class="btn btn-primary btn-small" data-dispute>Open a dispute</button></div><div class="empty-state"><div class="empty-icon">⚑</div><strong>No open disputes</strong><p>When something needs attention, you can track every response here.</p></div></section>`; }
function usersPanel() { const suspended = store.get('suspendedUsers', []); const isSuspended = email => suspended.includes(email); const action = email => `<button class="btn btn-outline btn-small" data-toggle-user="${email}">${isSuspended(email) ? 'Activate' : 'Suspend'}</button>`; return `<section class="panel"><div class="panel-header"><h2>Platform users</h2><span>1,284 total</span></div><div class="table-wrap"><table class="data-table"><thead><tr><th>User</th><th>Role</th><th>Verification</th><th>Action</th></tr></thead><tbody><tr><td><strong>Amaka Eze</strong><br><small>renter@werent.test</small></td><td>Renter</td><td><span class="status ${isSuspended('renter@werent.test') ? 'danger' : 'success'}">${isSuspended('renter@werent.test') ? 'Suspended' : 'Verified'}</span></td><td>${action('renter@werent.test')}</td></tr><tr><td><strong>Adewale Ibrahim</strong><br><small>landlord@werent.test</small></td><td>Landlord</td><td><span class="status ${isSuspended('landlord@werent.test') ? 'danger' : 'success'}">${isSuspended('landlord@werent.test') ? 'Suspended' : 'Verified'}</span></td><td>${action('landlord@werent.test')}</td></tr></tbody></table></div></section>`; }
function notificationsPanel() { const saved = store.get('notifications', []); const notifications = saved.length ? saved : [{ title: 'Caution fee requested', message: 'ABC Property Agency is waiting for your payment.', read: false }, { title: 'Inspection scheduled', message: 'Your inspection is tomorrow at 10:00am.', read: true }]; return `<section class="panel"><div class="panel-header"><h2>Notifications</h2><button class="btn btn-outline btn-small" id="mark-read">Mark all read</button></div><div class="timeline">${notifications.map(notification => `<div class="timeline-item"><span class="timeline-dot">${notification.read ? '◌' : '✦'}</span><div><strong>${escapeHtml(notification.title)}</strong><small>${escapeHtml(notification.message)}</small></div><span class="status ${notification.read ? '' : 'warning'}">${notification.read ? 'Read' : 'New'}</span></div>`).join('')}</div></section>`; }
function messagesPanel(role) { const messages = store.get('messages', [{ sender: role === 'renter' ? 'ABC Property Agency' : 'Amaka Eze', text: 'Hi, I wanted to confirm the inspection details for The Olive Courtyard.', date: 'Today, 9:42am' }]); return `<div class="dashboard-grid"><section class="panel"><div class="panel-header"><h2>Rental conversation</h2><span>${role === 'renter' ? 'With assigned agent' : 'With renter'}</span></div><div class="timeline">${messages.map(message => `<div class="timeline-item"><span class="timeline-dot">${initials(message.sender)}</span><div><strong>${escapeHtml(message.sender)}</strong><small>${escapeHtml(message.text)}</small></div><span class="status">${escapeHtml(message.date)}</span></div>`).join('')}</div></section><section class="panel"><div class="panel-header"><h2>Send a message</h2></div><form id="message-form"><div class="form-group"><label for="message-text">Message</label><textarea id="message-text" name="message" rows="5" required placeholder="Write a clear update..."></textarea></div><button class="btn btn-primary" type="submit">Send message ${icons.arrow}</button></form></section></div>`; }
function profilePanel() { const user = currentUser() || demoUsers.renter; const profile = store.get('profile', { name: user.name, phone: '', location: '' }); const verified = store.get('accountVerified', false); return `<div class="dashboard-grid"><section class="panel" style="max-width:680px"><div class="panel-header"><div><h2>Personal details</h2><span>Saved only in this frontend demo</span></div><span class="avatar">${initials(profile.name)}</span></div><form id="profile-form"><div class="form-group"><label for="profile-name">Full name</label><input id="profile-name" name="name" required value="${escapeHtml(profile.name)}"></div><div class="form-group"><label for="profile-email">Email address</label><input id="profile-email" value="${escapeHtml(user.email)}" disabled></div><div class="form-group"><label for="profile-phone">Phone number</label><input id="profile-phone" name="phone" value="${escapeHtml(profile.phone)}" placeholder="0800 000 0000"></div><div class="form-group"><label for="profile-location">Preferred location</label><input id="profile-location" name="location" value="${escapeHtml(profile.location)}" placeholder="e.g. Ibadan, Oyo State"></div><button class="btn btn-primary" type="submit">Save profile ${icons.arrow}</button></form></section><section class="panel"><div class="panel-header"><h2>Account security</h2></div><div class="callout"><strong>${verified ? 'Email verified' : 'Email not verified'}</strong>${verified ? 'Your demo account is marked as verified.' : 'Verify your demo account before sending important rental documents.'}</div><button class="btn btn-outline btn-small" style="margin-top:16px" data-verify-account>${verified ? 'Verified account' : 'Verify demo account'}</button><form id="password-form" style="margin-top:24px"><div class="form-group"><label for="new-password">New password</label><input id="new-password" name="password" type="password" minlength="6" required placeholder="Minimum 6 characters"></div><button class="btn btn-dark btn-small" type="submit">Update demo password</button></form></section></div>`; }
function setupPagination() { const results = document.getElementById('property-results'); if (!results) return; const cards = [...results.querySelectorAll('.property-card')]; const oldPagination = document.querySelector('.pagination'); oldPagination?.remove(); if (cards.length <= 4) return; let page = 1; const pageCount = Math.ceil(cards.length / 4); const pagination = document.createElement('div'); pagination.className = 'pagination'; pagination.innerHTML = `<button type="button" data-pagination="prev" aria-label="Previous page">Previous</button><span class="pagination-label" aria-live="polite"></span><button type="button" data-pagination="next" aria-label="Next page">Next</button>`; results.insertAdjacentElement('afterend', pagination); const update = () => { cards.forEach((card, index) => { const visible = index >= (page - 1) * 4 && index < page * 4; card.hidden = !visible; }); pagination.querySelector('.pagination-label').textContent = `Page ${page} of ${pageCount}`; pagination.querySelector('[data-pagination="prev"]').disabled = page === 1; pagination.querySelector('[data-pagination="next"]').disabled = page === pageCount; }; pagination.querySelector('[data-pagination="prev"]').addEventListener('click', () => { if (page > 1) { page -= 1; update(); } }); pagination.querySelector('[data-pagination="next"]').addEventListener('click', () => { if (page < pageCount) { page += 1; update(); } }); update(); }

function showProperty(id) { const property = properties.find(item => item.id === id); if (!property) return; const gallery = [property.image, ...properties.filter(item => item.id !== id).slice(0, 2).map(item => item.image)]; modal(`<div class="modal-header"><div><span class="badge badge-verified">✓ Verified listing</span><h2 style="margin-top:12px">${property.title}</h2><span class="location">${property.location}</span></div><button class="modal-close" data-close-modal>×</button></div><img id="gallery-main" class="gallery-main" src="${gallery[0]}" alt="${property.title}"><div class="gallery-thumbs">${gallery.map((image, index) => `<button class="gallery-thumb ${index === 0 ? 'active' : ''}" data-gallery-image="${image}" aria-label="View property image ${index + 1}"><img src="${image}" alt=""></button>`).join('')}</div><div class="property-meta"><span>▦ ${property.beds} bedrooms</span><span>⌂ ${property.baths} bathrooms</span><span>${property.type}</span></div><div class="payment-summary"><div class="payment-row"><span>Annual rent</span><strong class="price">${money(property.price)}</strong></div><div class="payment-row"><span>Property owner</span><strong>${property.owner}</strong></div><div class="payment-row"><span>Assigned agent</span><strong>${property.agent}</strong></div><div class="payment-row"><span>Caution fee</span><strong>${money(200000)}</strong></div><div class="payment-row"><span>Paid to / held by</span><strong style="color:var(--green)">Assigned agent</strong></div></div><div class="callout"><strong>Clear roles, clearer renting.</strong>${property.owner} owns this property. ${property.agent} is the assigned agent who receives and manages the caution fee.</div><div class="modal-actions"><button class="btn btn-outline" data-close-modal>Close</button><button class="btn btn-primary" data-apply="${property.id}">Apply for this home ${icons.arrow}</button></div>`); document.querySelectorAll('[data-gallery-image]').forEach(button => button.addEventListener('click', () => { document.getElementById('gallery-main').src = button.dataset.galleryImage; document.querySelectorAll('[data-gallery-image]').forEach(item => item.classList.remove('active')); button.classList.add('active'); })); document.querySelector('[data-apply]')?.addEventListener('click', () => showApplication(property.id)); }
function showPayment() { modal(`<div class="modal-header"><div><span class="eyebrow" style="margin:0;color:var(--green)">Secure demo checkout</span><h2 style="margin-top:10px">Caution fee payment</h2></div><button class="modal-close" data-close-modal>×</button></div><p style="color:var(--muted);font-size:13px;line-height:1.6">This is a frontend simulation. No real money will be moved.</p><div class="payment-summary"><div class="payment-row"><span>Property</span><strong>The Olive Courtyard · Bodija, Ibadan</strong></div><div class="payment-row"><span>Property owner</span><strong>Adewale Ibrahim</strong></div><div class="payment-row"><span>Assigned agent</span><strong>ABC Property Agency</strong></div><div class="payment-row"><span>Caution fee</span><strong class="price">${money(200000)}</strong></div><div class="payment-row"><span>Payment recipient</span><strong style="color:var(--green)">Assigned Agent</strong></div></div><form id="payment-form"><div class="form-group"><label for="payment-method">Payment method</label><select id="payment-method"><option>Demo bank transfer</option><option>Demo card</option></select></div><div class="callout"><strong>Important</strong>Your caution fee is paid to the assigned agent responsible for managing this rental transaction. The landlord is the property owner and is not the direct recipient.</div><div class="modal-actions"><button type="button" class="btn btn-outline" data-close-modal>Cancel</button><button type="submit" class="btn btn-primary">Confirm demo payment ${icons.arrow}</button></div></form>`); document.getElementById('payment-form')?.addEventListener('submit', event => { event.preventDefault(); const application = workflowState().application; application.status = 'Caution Fee Paid'; store.set('application', application); store.set('transaction', { id: `TX-${Date.now()}`, amount: 200000, status: 'Successful', recipient: 'Assigned Agent', date: new Date().toISOString() }); addNotification('Caution fee paid', 'Your payment was sent to the assigned agent in this demo.'); closeModal(); toast('Caution fee payment completed successfully.'); navigate('dashboard/payments'); }); }
function showReceipt() { const transaction = store.get('transaction', { id: 'TX-DEMO', date: new Date().toISOString() }); modal(`<div class="modal-header"><div><span class="badge badge-verified">✓ Payment successful</span><h2 style="margin-top:12px">Payment receipt</h2></div><button class="modal-close" data-close-modal>×</button></div><div class="payment-summary"><div class="payment-row"><span>Receipt number</span><strong>RC-${transaction.id.slice(-8)}</strong></div><div class="payment-row"><span>Transaction reference</span><strong>${transaction.id}</strong></div><div class="payment-row"><span>Date</span><strong>${new Date(transaction.date).toLocaleDateString('en-NG')}</strong></div><div class="payment-row"><span>Renter</span><strong>${currentUser()?.name || 'Amaka Eze'}</strong></div><div class="payment-row"><span>Property</span><strong>The Olive Courtyard</strong></div><div class="payment-row"><span>Landlord</span><strong>Adewale Ibrahim</strong></div><div class="payment-row"><span>Caution fee recipient</span><strong style="color:var(--green)">Assigned Agent</strong></div><div class="payment-row"><span>Amount</span><strong class="price">${money(transaction.amount || 200000)}</strong></div><div class="payment-row"><span>Payment status</span><span class="status success">Successful</span></div></div><div class="callout"><strong>Frontend demo receipt</strong>No real payment was processed. This receipt represents a simulated transaction for the weRent prototype.</div><div class="modal-actions"><button class="btn btn-outline" data-print-receipt>Print receipt</button><button class="btn btn-primary" data-close-modal>Done</button></div>`); document.querySelector('[data-print-receipt]')?.addEventListener('click', () => window.print()); }
function showApplication(propertyId) { const property = properties.find(item => item.id === propertyId) || properties[0]; modal(`<div class="modal-header"><div><span class="badge badge-verified">Application</span><h2 style="margin-top:12px">Apply for ${property.title}</h2></div><button class="modal-close" data-close-modal>×</button></div><form id="application-form"><div class="form-group"><label>Full name</label><input name="name" required value="${currentUser()?.name || ''}"></div><div class="form-group"><label>Why are you a good fit for this home?</label><textarea name="message" rows="4" required placeholder="Tell the landlord and agent a little about your move..."></textarea></div><div class="form-group"><label>Upload proof of income</label><input name="document" type="file" accept=".pdf,.png,.jpg"></div><div class="callout"><strong>Next steps</strong>We'll notify the assigned agent to begin document review. Your caution fee is only requested after the application reaches that stage.</div><div class="modal-actions"><button type="button" class="btn btn-outline" data-close-modal>Cancel</button><button type="submit" class="btn btn-primary">Submit application ${icons.arrow}</button></div></form>`); document.getElementById('application-form')?.addEventListener('submit', event => { event.preventDefault(); store.set('application', { propertyId, status: 'Submitted', createdAt: new Date().toISOString() }); addNotification('Application submitted', `Your application for ${property.title} was sent to the assigned agent.`); closeModal(); toast('Application submitted successfully.'); navigate('dashboard/applications'); }); }
function showApplicationDetails() { const state = workflowState(); const inspection = store.get('inspection', null); const steps = ['Submitted', 'Document Review', 'Inspection Scheduled', 'Awaiting Caution Fee', 'Caution Fee Paid', 'Approved']; const currentIndex = steps.indexOf(state.application.status); modal(`<div class="modal-header"><div><span class="badge badge-verified">Application timeline</span><h2 style="margin-top:12px">The Olive Courtyard</h2></div><button class="modal-close" data-close-modal>×</button></div><div class="payment-summary"><div class="payment-row"><span>Property owner</span><strong>Adewale Ibrahim</strong></div><div class="payment-row"><span>Assigned agent</span><strong>ABC Property Agency</strong></div><div class="payment-row"><span>Current stage</span><span class="status ${statusClass(state.application.status)}">${state.application.status}</span></div>${inspection ? `<div class="payment-row"><span>Inspection</span><strong>${inspection.date} · ${inspection.time}</strong></div>` : ''}</div><div class="timeline">${steps.map((step, index) => `<div class="timeline-item"><span class="timeline-dot">${index <= currentIndex ? '✓' : '○'}</span><div><strong>${step}</strong><small>${index <= currentIndex ? (index === currentIndex ? 'Current stage' : 'Completed') : 'Upcoming'}</small></div><span class="status ${index <= currentIndex ? 'success' : ''}">${index <= currentIndex ? 'Done' : 'Next'}</span></div>`).join('')}</div><div class="callout" style="margin-top:18px"><strong>Caution fee recipient: assigned agent</strong>The landlord owns the property. ABC Property Agency receives and manages the caution fee.</div><div class="modal-actions">${inspection ? '<button class="btn btn-outline" data-inspection>Reschedule inspection</button>' : ''}<button class="btn btn-primary" data-close-modal>Close</button></div>`); document.querySelector('[data-inspection]')?.addEventListener('click', showInspection); }
function showInspection() { const inspection = store.get('inspection', { date: 'Tomorrow', time: '10:00am' }); modal(`<div class="modal-header"><div><span class="badge badge-verified">Inspection</span><h2 style="margin-top:12px">Schedule inspection</h2></div><button class="modal-close" data-close-modal>×</button></div><form id="inspection-form"><div class="form-group"><label for="inspection-date">Date</label><input id="inspection-date" name="date" type="date" required></div><div class="form-group"><label for="inspection-time">Time</label><select id="inspection-time" name="time"><option>9:00am</option><option>10:00am</option><option>12:00pm</option><option>2:00pm</option><option>4:00pm</option></select></div><div class="callout"><strong>Inspection contact</strong>ABC Property Agency will coordinate this visit. The landlord remains the property owner.</div><div class="modal-actions"><button type="button" class="btn btn-outline" data-close-modal>Cancel</button><button class="btn btn-primary" type="submit">Save inspection ${icons.arrow}</button></div></form>`); document.getElementById('inspection-time').value = inspection.time; document.getElementById('inspection-form')?.addEventListener('submit', event => { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); store.set('inspection', { ...data, status: 'Scheduled' }); addNotification('Inspection updated', `Your inspection is scheduled for ${data.date} at ${data.time}.`); closeModal(); toast('Inspection schedule updated.'); }); }
function showRefund() { modal(`<div class="modal-header"><div><span class="badge badge-orange">Refund workflow</span><h2 style="margin-top:12px">Request a caution-fee refund</h2></div><button class="modal-close" data-close-modal>×</button></div><form id="refund-form"><div class="form-group"><label>Reason for refund</label><select required><option value="">Select a reason</option><option>Application withdrawn</option><option>Property was unavailable</option><option>Agreement ended</option></select></div><div class="form-group"><label>Additional details</label><textarea rows="4" required placeholder="Share context for the assigned agent and admin reviewer."></textarea></div><div class="callout"><strong>What happens next</strong>Your assigned agent reviews the request first, then forwards it to admin for approval.</div><div class="modal-actions"><button type="button" class="btn btn-outline" data-close-modal>Cancel</button><button type="submit" class="btn btn-primary">Submit request ${icons.arrow}</button></div></form>`); document.getElementById('refund-form')?.addEventListener('submit', event => { event.preventDefault(); store.set('refundRequest', { status: 'Refund Requested', date: new Date().toISOString() }); addNotification('Refund requested', 'Your caution-fee refund request was submitted for agent review.'); closeModal(); toast('Refund request submitted for review.'); }); }
function showDispute() { modal(`<div class="modal-header"><div><span class="badge badge-orange">Support</span><h2 style="margin-top:12px">Open a dispute</h2></div><button class="modal-close" data-close-modal>×</button></div><form id="dispute-form"><div class="form-group"><label>Reason</label><select required><option value="">Choose a reason</option><option>Payment issue</option><option>Property condition</option><option>Communication issue</option><option>Agreement concern</option></select></div><div class="form-group"><label>What happened?</label><textarea rows="5" required placeholder="Describe the issue clearly."></textarea></div><div class="modal-actions"><button type="button" class="btn btn-outline" data-close-modal>Cancel</button><button type="submit" class="btn btn-primary">Open dispute ${icons.arrow}</button></div></form>`); document.getElementById('dispute-form')?.addEventListener('submit', event => { event.preventDefault(); store.set('dispute', { status: 'Open', date: new Date().toISOString() }); addNotification('Dispute opened', 'Your support case is now open for review.'); closeModal(); toast('Dispute opened. Our team will review it.'); }); }
function showMaintenance() { modal(`<div class="modal-header"><div><span class="badge badge-orange">Tenancy support</span><h2 style="margin-top:12px">Report a maintenance issue</h2></div><button class="modal-close" data-close-modal>×</button></div><form id="maintenance-form"><div class="form-group"><label for="issue-type">Issue type</label><select id="issue-type" name="type" required><option value="">Select an issue</option><option>Plumbing or water</option><option>Power or electricity</option><option>Appliance or fixture</option><option>Security concern</option><option>Other</option></select></div><div class="form-group"><label for="issue-description">Description</label><textarea id="issue-description" name="description" rows="5" required placeholder="Describe what needs attention..."></textarea></div><div class="callout"><strong>What happens next</strong>Your assigned agent will receive this issue and coordinate the next response.</div><div class="modal-actions"><button type="button" class="btn btn-outline" data-close-modal>Cancel</button><button class="btn btn-primary" type="submit">Submit issue ${icons.arrow}</button></div></form>`); document.getElementById('maintenance-form')?.addEventListener('submit', event => { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); const issues = store.get('maintenanceIssues', []); issues.push({ ...data, status: 'Open', date: new Date().toISOString() }); store.set('maintenanceIssues', issues); addNotification('Maintenance issue reported', 'Your assigned agent has been notified.'); closeModal(); toast('Maintenance issue submitted.'); }); }
function showAddProperty() { modal(`<div class="modal-header"><div><span class="badge badge-verified">Landlord tools</span><h2 style="margin-top:12px">Add a property</h2></div><button class="modal-close" data-close-modal>×</button></div><form id="property-form"><div class="form-group"><label for="property-title">Property name</label><input id="property-title" name="title" required placeholder="e.g. Garden View Duplex"></div><div class="form-group"><label for="property-location">Location</label><input id="property-location" name="location" required placeholder="Area, city"></div><div class="form-group"><label for="property-type">Property type</label><select id="property-type" name="type"><option>2 Bedroom Apartment</option><option>3 Bedroom Duplex</option><option>Detached House</option><option>Self Contained Apartment</option></select></div><div class="form-group"><label for="property-price">Annual rent (₦)</label><input id="property-price" name="price" type="number" min="1" required placeholder="2500000"></div><div class="callout"><strong>Verification reminder</strong>Your listing will appear as under review until the weRent verification process is connected to a backend.</div><div class="modal-actions"><button type="button" class="btn btn-outline" data-close-modal>Cancel</button><button type="submit" class="btn btn-primary">Save property ${icons.arrow}</button></div></form>`); document.getElementById('property-form')?.addEventListener('submit', event => { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); const managed = store.get('managedProperties', properties.filter(property => property.owner === currentUser()?.name)); managed.push({ id: `WR-${Date.now().toString().slice(-5)}`, title: data.title, location: data.location, type: data.type, price: Number(data.price), beds: Number(data.type[0]) || 1, baths: Number(data.type[0]) || 1, image: properties[0].image, verified: false, owner: currentUser()?.name || 'Demo landlord', agent: 'Pending assignment' }); store.set('managedProperties', managed); addNotification('Property submitted', `${data.title} is queued for admin verification.`); closeModal(); toast('Property saved and queued for verification.'); navigate('dashboard/properties'); }); }
function showEditProperty(id) { const managed = store.get('managedProperties', []); const property = managed.find(item => item.id === id); if (!property) return; modal(`<div class="modal-header"><div><span class="badge badge-verified">Landlord tools</span><h2 style="margin-top:12px">Edit listing</h2></div><button class="modal-close" data-close-modal>×</button></div><form id="edit-property-form"><div class="form-group"><label for="edit-title">Property name</label><input id="edit-title" name="title" required value="${escapeHtml(property.title)}"></div><div class="form-group"><label for="edit-location">Location</label><input id="edit-location" name="location" required value="${escapeHtml(property.location)}"></div><div class="form-group"><label for="edit-price">Annual rent (₦)</label><input id="edit-price" name="price" type="number" min="1" required value="${property.price}"></div><div class="modal-actions"><button type="button" class="btn btn-outline" data-close-modal>Cancel</button><button type="submit" class="btn btn-primary">Save changes ${icons.arrow}</button></div></form>`); document.getElementById('edit-property-form')?.addEventListener('submit', event => { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); property.title = data.title; property.location = data.location; property.price = Number(data.price); property.verified = false; store.set('managedProperties', managed); addNotification('Property updated', `${property.title} was sent back for verification.`); closeModal(); toast('Listing updated and queued for re-verification.'); navigate('dashboard/properties'); }); }
function toggleManagedProperty(id) { const managed = store.get('managedProperties', []); const property = managed.find(item => item.id === id); if (!property) return; property.active = property.active === false; store.set('managedProperties', managed); toast(property.active === false ? 'Property deactivated.' : 'Property activated.'); render(); }

function render() { const hash = window.location.hash.slice(1) || 'home'; const [route, queryString = ''] = hash.split('?'); let html = route === 'home' ? homeView() : route === 'properties' ? propertiesView(queryString) : route === 'settings' ? settingsView() : route === 'company-about' ? infoPageView('about') : route === 'privacy-policy' ? infoPageView('privacy') : route === 'support' ? infoPageView('support') : route === 'owners' ? infoPageView('owners') : route === 'list-property' ? infoPageView('listProperty') : route === 'meet-agent' ? infoPageView('meetAgent') : route === 'auth-login' ? authView('login') : route === 'auth-signup' ? authView('signup') : route === 'auth-forgot' ? forgotPasswordView() : route.startsWith('dashboard') ? dashboardView(route.split('/')[1] || 'overview') : homeView(); document.getElementById('app').innerHTML = html; bindEvents(); }
function bindEvents() {
  document.body.classList.toggle('compact-dashboard', store.get('settings', { compact: false }).compact === true);
  setupRolePicker();
  setupHeroCarousel();
  setupLazyImages();
  if (currentUser()?.role === 'admin' && document.querySelector('.sidebar nav') && !document.querySelector('.sidebar [data-settings-link]')) { const settingsLink = document.createElement('a'); settingsLink.href = '#settings'; settingsLink.className = 'side-link'; settingsLink.dataset.settingsLink = 'true'; settingsLink.innerHTML = '<span>⚙</span><span>Settings</span>'; document.querySelector('.sidebar nav').appendChild(settingsLink); }
  document.querySelectorAll('.mobile-menu').forEach(button => button.addEventListener('click', () => toggleMobileMenu(button)));
  document.querySelectorAll('[data-layout]').forEach(button => button.addEventListener('click', () => { store.set('propertyLayout', button.dataset.layout); const results = document.getElementById('property-results'); results?.classList.toggle('list-view', button.dataset.layout === 'list'); document.querySelectorAll('[data-layout]').forEach(item => item.classList.toggle('active', item === button)); }));
  setupPagination();
  document.querySelectorAll('[data-view]').forEach(button => button.addEventListener('click', () => navigate(button.dataset.view)));
  document.querySelectorAll('[data-property]').forEach(button => button.addEventListener('click', () => showProperty(button.dataset.property)));
  document.querySelectorAll('[data-application-details]').forEach(button => button.addEventListener('click', showApplicationDetails));
  document.querySelectorAll('[data-auth]').forEach(button => button.addEventListener('click', () => navigate(`auth-${button.dataset.auth}`)));
  document.querySelectorAll('[data-favorite]').forEach(button => button.addEventListener('click', () => { const id = button.dataset.favorite; const saved = store.get('savedProperties', []); store.set('savedProperties', saved.includes(id) ? saved.filter(item => item !== id) : [...saved, id]); toast(saved.includes(id) ? 'Removed from saved homes.' : 'Saved to your homes.'); render(); }));
  document.querySelectorAll('[data-payment]').forEach(button => button.addEventListener('click', showPayment));
  document.querySelectorAll('[data-receipt]').forEach(button => button.addEventListener('click', showReceipt));
  document.querySelectorAll('[data-refund]').forEach(button => button.addEventListener('click', showRefund));
  document.querySelectorAll('[data-dispute]').forEach(button => button.addEventListener('click', showDispute));
  document.querySelectorAll('[data-maintenance]').forEach(button => button.addEventListener('click', event => { event.preventDefault(); event.stopPropagation(); showMaintenance(); }));
  document.querySelectorAll('[data-add-property]').forEach(button => button.addEventListener('click', showAddProperty));
  document.querySelectorAll('[data-edit-property]').forEach(button => button.addEventListener('click', () => showEditProperty(button.dataset.editProperty)));
  document.querySelectorAll('[data-toggle-property]').forEach(button => button.addEventListener('click', () => toggleManagedProperty(button.dataset.toggleProperty)));
  document.querySelectorAll('[data-toggle-user]').forEach(button => button.addEventListener('click', () => { const email = button.dataset.toggleUser; const suspended = store.get('suspendedUsers', []); const nextSuspended = suspended.includes(email) ? suspended.filter(item => item !== email) : [...suspended, email]; store.set('suspendedUsers', nextSuspended); addAudit(nextSuspended.includes(email) ? 'User suspended' : 'User activated', email); addNotification('User status updated', `${email} account status was changed by admin.`); toast(suspended.includes(email) ? 'User activated.' : 'User suspended.'); render(); }));
  document.querySelectorAll('[data-workflow]').forEach(button => button.addEventListener('click', () => updateWorkflow(button.dataset.workflow, button.dataset.propertyId)));
  document.querySelectorAll('[data-close-modal]').forEach(button => button.addEventListener('click', closeModal));
  document.getElementById('header-signout')?.addEventListener('click', () => { store.set('currentUser', null); toast('You have been signed out.'); navigate('home'); });
  document.getElementById('logout')?.addEventListener('click', () => { store.set('currentUser', null); toast('You have been signed out.'); navigate('home'); });
  document.getElementById('hero-search')?.addEventListener('submit', event => { event.preventDefault(); const data = new FormData(event.currentTarget); const params = new URLSearchParams({ location: data.get('location') || '', type: data.get('type') || '', budget: data.get('budget') || '' }); navigate(`properties?${params.toString()}`); });
  document.getElementById('filter-form')?.addEventListener('submit', event => { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); const result = filterProperties(data); const resultsEl = document.getElementById('property-results'); if (resultsEl) { resultsEl.innerHTML = result.length ? result.map(propertyCard).join('') : '<div class="panel empty-state" style="grid-column:1/-1"><div class="empty-icon">⌕</div><strong>No matching homes found.</strong><p>Try a different city, property type, or budget.</p></div>'; } const copyEl = document.getElementById('results-copy'); if (copyEl) { copyEl.textContent = `${result.length} homes match your search`; } bindEvents(); });
  document.getElementById('auth-form')?.addEventListener('submit', event => { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); const existing = Object.values(demoUsers).find(user => user.email === data.email && user.password === data.password); const user = existing || { name: data.name || 'Demo renter', email: data.email, role: data.role || 'renter' }; store.set('currentUser', user); toast(`Welcome to weRent, ${user.name.split(' ')[0]}.`); navigate('dashboard/overview'); });
  document.getElementById('forgot-form')?.addEventListener('submit', event => { event.preventDefault(); toast('Demo reset link generated. Check your inbox when connected to an API.'); navigate('auth-login'); });
  document.getElementById('settings-form')?.addEventListener('submit', event => { event.preventDefault(); const data = new FormData(event.currentTarget); store.set('settings', { notifications: data.has('notifications'), verification: data.has('verification'), compact: data.has('compact') }); toast('Settings saved locally.'); });
  document.getElementById('reset-demo')?.addEventListener('click', () => { ['application', 'transaction', 'refundRequest', 'maintenanceIssues', 'messages', 'notifications', 'managedProperties', 'auditLogs'].forEach(key => localStorage.removeItem(`weRent_${key}`)); toast('Demo workflow data reset.'); });
  document.getElementById('message-form')?.addEventListener('submit', event => { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); const messages = store.get('messages', []); messages.push({ sender: currentUser()?.name || 'Demo user', text: data.message, date: 'Just now' }); store.set('messages', messages); addNotification('New message sent', 'Your rental conversation has been updated.'); toast('Message sent.'); render(); });
  document.getElementById('profile-form')?.addEventListener('submit', event => { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); const user = currentUser() || demoUsers.renter; store.set('profile', data); store.set('currentUser', { ...user, name: data.name }); addNotification('Profile updated', 'Your personal details were saved.'); toast('Profile updated successfully.'); render(); });
  document.querySelector('[data-verify-account]')?.addEventListener('click', () => { store.set('accountVerified', true); addAudit('Account verified', currentUser()?.email || 'Demo user verified account'); addNotification('Account verified', 'Your weRent demo account is now marked as verified.'); toast('Demo account verified.'); render(); });
  document.getElementById('password-form')?.addEventListener('submit', event => { event.preventDefault(); store.set('demoPasswordUpdated', true); toast('Demo password updated locally.'); event.currentTarget.reset(); });
  document.querySelector('[data-print-report]')?.addEventListener('click', () => window.print());
  document.getElementById('application-form')?.addEventListener('submit', event => { event.preventDefault(); store.set('application', { status: 'Submitted', createdAt: new Date().toISOString() }); closeModal(); toast('Application submitted successfully.'); navigate('dashboard/applications'); });
  document.getElementById('payment-form')?.addEventListener('submit', event => { event.preventDefault(); store.set('transaction', { id: `TX-${Date.now()}`, amount: 200000, status: 'Successful', recipient: 'Assigned Agent', date: new Date().toISOString() }); closeModal(); toast('Caution fee payment completed successfully.'); navigate('dashboard/payments'); });
  document.getElementById('refund-form')?.addEventListener('submit', event => { event.preventDefault(); store.set('refundRequest', { status: 'Refund Requested', date: new Date().toISOString() }); closeModal(); toast('Refund request submitted for review.'); });
  document.getElementById('dispute-form')?.addEventListener('submit', event => { event.preventDefault(); store.set('dispute', { status: 'Open', date: new Date().toISOString() }); closeModal(); toast('Dispute opened. Our team will review it.'); });
  document.getElementById('mark-read')?.addEventListener('click', () => { const notifications = store.get('notifications', []).map(notification => ({ ...notification, read: true })); store.set('notifications', notifications); toast('Notifications marked as read.'); render(); });
}
document.addEventListener('keydown', event => { const dialog = document.querySelector('.modal'); if (!dialog) return; if (event.key === 'Escape') { closeModal(); return; } if (event.key !== 'Tab') return; const focusable = [...dialog.querySelectorAll('button, input, select, textarea, a[href]')].filter(element => !element.disabled); if (!focusable.length) return; const first = focusable[0]; const last = focusable[focusable.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); } });
window.addEventListener('hashchange', render); render();
